<!-- Begin: Footer.inc -->
<br />
<table cellpadding="0" cellspacing="0" class="pagebottom_border">
    <tr>
        <td>
        </td>
    </tr>
</table>
<table cellpadding="0" cellspacing="0" class="pagebottom_menu">
    <tr>
        <td>
            <br>
            <a href="http://anytickets.com">Home</a>&nbsp;&middot;&nbsp;<a href="http://anytickets.com/sports">Sports</a>&nbsp;&middot;&nbsp;<a href="http://anytickets.com/concerts">Concerts</a>&nbsp;&middot;&nbsp;
            <a href="http://anytickets.com/theater">Theater</a>&nbsp;&nbsp;&middot;
            <a href="http://anytickets.com/static/about_us">About Us</a>&nbsp;&nbsp;&middot;
            <a href="http://anytickets.com//static/privacy_policy">Privacy Policy</a>&nbsp;&nbsp;
                </td>
    </tr>
</table>
<table cellpadding="0" cellspacing="0" class="pagebottom_info">
    <tr>
        <td>
            Copyright&nbsp;&nbsp;<script language="javascript">
            var today = new Date();
            var year = today.getYear();
            if(year > 2000)
            {
            document.write(year);
            }
            else
            {
            year = year + 1900;
            document.write(year);
            }
            </script><br>
            anytickets.com<br>
            All Rights Reserved
        </td>
    </tr>
</table>
<!-- End: Footer.inc -->