<!-- Begin: LogoBar.inc -->
<div id="main-navigation" class="navbar css3">
    <ul class="nav clearfix">
        <li class="active first">
            <a href="http://anytickets.com">
                HOME
            </a>
        </li>
        <li class="">
            <a href="http://anytickets.com/sports">
                SPORTS
            </a>
        </li>
        <li class="">
            <a href="http://anytickets.com/concerts">
                CONCERTS
            </a>
        </li>
        <li class="">
            <a href="http://anytickets.com/theater">
                THEATER
            </a>
        </li>
    </ul>
</div>
<!-- End: LogoBar.inc -->