<!-- Begin: SideBarLeft.inc -->
<div style="width: 100%;">
    <br />
 
    <table border="0" width="100%" cellpadding="0" cellspacing="0" align="center">
        <tr>
            <td width="16">
                <img src="Brokers/00000-000/Images/EZ6UL.gif" /></td>
            <td width="16" background="Brokers/00000-000/Images/EZ6TOP.gif">
            </td>
            <td width="16">
                <img src="Brokers/00000-000/Images/EZ6UR.gif" /></td>
        </tr>
        <tr>
            <td width="16" background="Brokers/00000-000/Images/EZ6LEFT.gif">
            </td>
            <td width="100%" height="" background="Brokers/00000-000/Images/EZ6CENTER.gif">
                <div style="text-align: center;">
                    <img src="Brokers/00000-000/Images/sidebar_purchasenotes.gif" alt="Purchase Notes" />
                </div>
                <div style="text-align: left; padding-top: 5px;" class="purchase_notes">
                    A return e-mail, which states that your credit card has been charged for your order,
                    serves as acceptance of your offer to purchase tickets.<br /><br />
                </div>
                <div style="text-align: left; padding-top: 5px;" class="purchase_notes">
                    All sales are final.<br>
                    There are no refunds, exchanges or cancellations. If the event is postponed, tickets
                    will be honored for the rescheduled date.
                </div>
            </td>
            <td width="16" background="Brokers/00000-000/Images/EZ6RIGHT.gif">
            </td>
        </tr>
        <tr>
            <td width="16">
                <img src="Brokers/00000-000/Images/EZ6LL.gif" /></td>
            <td width="16" background="Brokers/00000-000/Images/EZ6BOT.gif">
            </td>
            <td width="16">
                <img src="Brokers/00000-000/Images/EZ6LR.gif" /></td>
        </tr>
    </table>
</div>
 <br><p align="center">
 <!--extra buttons -->
</p>
                        
<!-- End: SideBarLeft.inc -->
